//
// Generated file, do not edit! Created by nedtool 5.6 from Data.msg.
//

#ifndef __DATA_M_H
#define __DATA_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Data.msg:1</tt> by nedtool.
 * <pre>
 * packet Data
 * {
 *     name = "Data";
 *     string dsc;
 *     string src;
 *     int seq;
 *     byteLength = 6;
 * }
 * </pre>
 */
class Data : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string dsc;
    ::omnetpp::opp_string src;
    int seq;

  private:
    void copy(const Data& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Data&);

  public:
    Data(const char *name=nullptr, short kind=0);
    Data(const Data& other);
    virtual ~Data();
    Data& operator=(const Data& other);
    virtual Data *dup() const override {return new Data(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getDsc() const;
    virtual void setDsc(const char * dsc);
    virtual const char * getSrc() const;
    virtual void setSrc(const char * src);
    virtual int getSeq() const;
    virtual void setSeq(int seq);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const Data& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, Data& obj) {obj.parsimUnpack(b);}


#endif // ifndef __DATA_M_H

